/*
  Status: prototype
  Process: API generation
*/

//----------------------------------------------------------------------------//
// This unit was automatically generated by the RemObjects SDK after reading  //
// the RODL file associated with this project .                               //
//                                                                            //
// Do not modify this unit manually, or your changes will be lost when this   //
// unit is regenerated the next time you compile the project.                 //
//----------------------------------------------------------------------------//


/* This codegen depends on RemObjectsSDK.js
* Usage:
* var Channel = new RemObjects.SDK.HTTPClientChannel("http://localhost:8099/JSON");
* var Message = new RemObjects.SDK.JSONMessage();
* var Service = new NewService(Channel, Message);
* Service.Sum(1, 2,
*             function(result) {
*                 alert(result);
*             },
*             function(msg) {alert(msg.getErrorMessage())}
* );
* 
*/

// <%%% START ENUMS %%%>
// Enum: %ENUM_NAME_UNSAFE%
function %ENUM_NAME%() {
  this.value = null;
};
%ENUM_NAME%.prototype = new RemObjects.SDK.ROEnumType();
%ENUM_NAME%.prototype.enumValues = [
    // <%%% START VALUES %%%>
    "%VALUE_NAME_NOPREFIX%",
    // <%%% END VALUES %%%>
	];
%ENUM_NAME%.prototype.constructor = %ENUM_NAME%;
RemObjects.SDK.RTTI["%ENUM_NAME%"] = %ENUM_NAME%;

// <%%% END ENUMS %%%>

// <%%% START STRUCTS %%%>
// Struct: %STRUCT_NAME_UNSAFE%
function %STRUCT_NAME%() {
// <%%% START IF_HAS_FIELDS %%%>
// <%%% START ENTIRE_HIERARCHY_FIELDS %%%>
    this.%FIELD_NAME% = {dataType : "%FIELD_TYPE%", value : null};
// <%%% END ENTIRE_HIERARCHY_FIELDS %%%>
// <%%% END IF_HAS_FIELDS %%%>
};
%STRUCT_NAME%.prototype = new RemObjects.SDK.ROStructType();
%STRUCT_NAME%.prototype.constructor = %STRUCT_NAME%;
RemObjects.SDK.RTTI["%STRUCT_NAME%"] = %STRUCT_NAME%;

// <%%% END STRUCTS %%%>

// <%%% START ARRAYS %%%>
// Array: %ARRAY_NAME_UNSAFE%
function %ARRAY_NAME%() {
  RemObjects.SDK.ROArrayType.call(this);
  this.elementType = "%ARRAY_TYPE%";
};
%ARRAY_NAME%.prototype = new RemObjects.SDK.ROArrayType();
%ARRAY_NAME%.prototype.constructor = %ARRAY_NAME%;
RemObjects.SDK.RTTI["%ARRAY_NAME%"] = %ARRAY_NAME%;

// <%%% END ARRAYS %%%>

// <%%% START EXCEPTIONS %%%>
// Exception: %EXCEPTION_NAME%
function %EXCEPTION_NAME%(e) {
    RemObjects.SDK.ROException.call(this, e);
    // <%%% START FIELDS_NO_STRIP %%%>
    this.fields.%FIELD_NAME%  = {dataType : "%FIELD_TYPE%", value : null};
    // <%%% END FIELDS_NO_STRIP %%%>
};
%EXCEPTION_NAME%.prototype = new RemObjects.SDK.ROException();
RemObjects.SDK.RTTI["%EXCEPTION_NAME%"] = %EXCEPTION_NAME%;


// <%%% END EXCEPTIONS %%%>

// <%%% START SERVICES %%%>
// Service: %SERVICE_NAME_UNSAFE%
function %SERVICE_NAME%(__channel, __message, __service_name) {
  RemObjects.SDK.ROService.call(this, __channel, __message, __service_name);
  this.fServiceName = this.fServiceName || __service_name || "%SERVICE_NAME_UNSAFE%";
};

// <%%% START IF_SERVICE_HAS_ANCESTOR %%%>
%SERVICE_NAME%.prototype = new %SERVICE_ANCESTOR_NAME%();
// <%%% END IF_SERVICE_HAS_ANCESTOR %%%>

// <%%% START OPERATIONS %%%>
%SERVICE_NAME%.prototype.%OPERATION_NAME_UNSAFE% = function(
	// <%%% START IN_PARAMS_NO_STRIP %%%>
	%PARAM_NAME%,
	// <%%% END IN_PARAMS_NO_STRIP %%%>	
	__success, __error) {
    try {
        var msg = this.fMessage.clone();
        msg.initialize(this.fServiceName, "%OPERATION_NAME_UNSAFE%");
        // <%%% START IN_PARAMS_NO_STRIP %%%>
        msg.write("%PARAM_NAME_UNSAFE%", "%PARAM_TYPE%", %PARAM_NAME%);
	// <%%% END IN_PARAMS_NO_STRIP %%%>
        msg.finalize();
        this.fChannel.dispatch(msg, function (__message) {
	// <%%% START IF_OPERATION_HAS_RESULT %%%>
		var __result = __message.read("%OPERATION_RESULT_NAME%", "%OPERATION_RESULT_TYPE_NAME%");
	// <%%% END IF_OPERATION_HAS_RESULT %%%>
	// <%%% START OUT_PARAMS_NO_STRIP %%%>
	__%PARAM_NAME% = __message.read("%PARAM_NAME_UNSAFE%", "%PARAM_TYPE%");
	// <%%% END OUT_PARAMS_NO_STRIP %%%>	
	        __success(
	// <%%% START IF_OPERATION_HAS_RESULT %%%>
		__result
	// <%%% START IF_OPERATION_HAS_OUT_PARAMS %%%>
		,
	// <%%% END IF_OPERATION_HAS_OUT_PARAMS %%%>
	// <%%% END IF_OPERATION_HAS_RESULT %%%>
	// <%%% START OUT_PARAMS %%%>
		__%PARAM_NAME%,
	// <%%% END OUT_PARAMS %%%>	
		);
        }, __error);

    } catch (e) {
        __error(msg, e);
    };
};

// <%%% END OPERATIONS %%%>

// <%%% END SERVICES %%%>

// <%%% START EVENT_SINKS %%%>
// Event sink: %EVENT_SINK_NAME_UNSAFE%
function %EVENT_SINK_NAME_UNSAFE%() {
  // <%%% START OPERATIONS %%%>
	this.%OPERATION_NAME% = {
	// <%%% START PARAMS %%%>
		%PARAM_NAME% : {dataType : "%PARAM_TYPE%", value : null},
	// <%%% END PARAMS %%%>
	};
	// <%%% END OPERATIONS %%%>
};
%EVENT_SINK_NAME_UNSAFE%.prototype = new RemObjects.SDK.ROEventSink();
%EVENT_SINK_NAME_UNSAFE%.prototype.constructor = %EVENT_SINK_NAME_UNSAFE%;
RemObjects.SDK.RTTI["%EVENT_SINK_NAME_UNSAFE%"] = %EVENT_SINK_NAME_UNSAFE%;

// <%%% END EVENT_SINKS %%%>
